### PR TITLE
Git clone depth

### PR DESCRIPTION
**Pull request by gforcada**
Fixes https://github.com/fschulze/mr.developer/issues/163

@fschulze how can I add a test for it? Can I improve it somehow?

### CODE REVIEW

**Comment by fschulze** [comment]
For the tests look at ``test_git.py``, you would create a repository, check it out with the ```depth`` option and then use some git command to check that only the specified number of revisions are checked out (not sure how you see that, maybe git log).

**Comment by fschulze** [comment]
Looks good overall so far. Please add a changelog entry with your name when you are done.

**Comment by gforcada** [comment]
Thanks for the comments! I will try to get around them today or tomorrow.

**Comment by rghv** [comment]
Was working on this feature and saw this PR! This would be very useful for all those build jobs with buildout configs that still rely on mr.developer to do source checkout. :+1: for this feature! Thanks, @gforcada!

**Comment by gforcada** [comment]
@fschulze I fixed everything, added the changelog and I'm working on the test (see the last commit).

Any idea on why it fails? I keep trying on my own...

**Comment by gforcada** [comment]
@fschulze finally! tests for all python versions pass, would it be ok to merge it already? And a release soon afterwards would be great :)

**Comment by fschulze** [comment]
Thanks for rebasing the commits to keep the history clean!

**Comment by gforcada** [comment]
@fschulze no problem, I **do** like a clean history, now we need a release and maybe a test for the global option? I didn't see how to test it...

**Comment by gforcada** [comment]
Oh I see the release, sorry! thanks a lot!

**Pull request merged**
