### PR TITLE
Checkout branch on clone

### PR DESCRIPTION
**Pull request by gforcada**
If a source defines a branch, switch to it when cloning.

This helps when used in combination with ``--depth``, as git will already
download the history defined by ``--depth`` from that branch instead of
master.

### CODE REVIEW

**Comment by fschulze** [comment]
Could you add a changelog entry, please?

And maybe a test? In general we need more tests for git to fix some of the outstanding issues, so this would be a good place to start :)

**Comment by gforcada** [comment]
Changelog entry added.

As for the tests, it seems just too much work to make them. Maybe we need some abstraction layer to help work on them (sorry no time for that)? But I remember my last pull request where I spent 30% of the time working on the issue at hand and 70% of the time trying to make the test and running them (that was also a major pain).

**Comment by fschulze** [comment]
In general that's a pretty normal code to test ratio for me. But everytime I do refactoring I love having the tests.

Any suggestions for the abstraction layer?

**Comment by mauritsvanrees** [comment]
Closing this one in favor of pull request #169.

**Pull request closed without merging**
