### PR TITLE
Make commands extensible

### PR DESCRIPTION
**Pull request by do3cc**
Commands are now added via entry points.
I want to be able to extend mr.developer via third party packages.
One of the use cases I have in mind is using a workflow with integration and feature branches where I can merge/rebase/reset branches in multiple repositories at once.
I'd like to name the commands explicitly and not in such a generic way that they might be usable in a generic way but quite hard to use to implement my specific workflow. For these use cases, having extensible commands is an advantage.
@saily @tisto

### CODE REVIEW

**Comment by fschulze** [comment]
In general I'd like a proper plugin system, but I think it is too verbose this way. You should checkout how devpi and py.test handle plugin hooks, I use something similar but less nice in ploy as well. @hpk42 and I wanted to factor out the hook system from py.test anyway, since it's really useful.

**Comment by do3cc** [comment]
I am fine with whatever implementation allows me to add commands. I've read the docs of pytest plugins, it doesn't sound too different. Is there already something in the making, or are there concrete plans?

**Comment by do3cc** [comment]
Travis found a real test failure, a test method that does not exist in Python 2.6. Before I fix this, lets see what will actually be the way to go with plugins

**Comment by fschulze** [comment]
You know what, mr.developer already uses entry points similar to what you did. Let's just go for it.

But could you split the commit, so the move of the exiting commands into the new file is it's own commit without any other changes? Makes it easier to see what actually changed. Or just keep them where they are. If you do, please do a force push with the new commits.

**Comment by do3cc** [comment]
Was this type of refactoring what you had in mind?
Also, I going to fix the test failure too, of course

**Comment by fschulze** [comment]
Yes, thanks!

**Comment by do3cc** [comment]
No its good

**Comment by tisto** [comment]
Can we add some documentation how to use this?

**Pull request merged**
