### PR TITLE
Add documentation on extension points

### PR DESCRIPTION
**Pull request by do3cc**
@fschulze Can you help me with the wording here? I believe I should not talk about VCS providers for example.

@tisto

### CODE REVIEW

**Comment by fschulze** [comment]
What do you mean with "not talk about VCS providers"?

**Comment by do3cc** [comment]
The term is not used in the documentation so far. The Code calls the different implementations working_copies which I find confusing as a term. I just don't want to introduce new names for things and want to know, what name you suggest.

**Comment by fschulze** [comment]
Ah, I'd go for "version control system" then. If you use the abbreviation, you would have to use VCSs or VCS's, which both look awkward IMO. The term isn't used that often, so just write it out.

**Comment by do3cc** [comment]
I went for working copy where it made sense. I could not bring myself to write out VCS though. It exists once in the text. I think it is good now.

**Pull request merged**
