### PR TITLE
Add codeanalysis plugin

### PR DESCRIPTION
**Pull request by do3cc**
I added it with the least invasive configuration.
No errors and no commit hook.
I used it for my other plugin, to detect unused imports

### CODE REVIEW

**Comment by do3cc** [comment]
For my other PR, not Plugin

**Comment by do3cc** [comment]
Travis CI failed with ssl error, no test failure

**Comment by do3cc** [comment]
Do you have an interest in getting mr.developer pep8 compatible without any pep8 exceptions?
If you are not opposed to the idea I'd like to crank up the checks from codeanalysis and fix the exceptions. That excludes 80 chars limit and indentation. If you prefer the code the way it is, I leave it as is.

**Comment by fschulze** [comment]
What is the difference to pytest-pep8 and pytest-flakes? I just checked and realized they aren't enabled in tox.ini yet, even though they are installed. In other projects I use them all the time and my editor warns me as well. In general I only fix up things in places I touch during other changes anyway.

**Comment by do3cc** [comment]
it is just another way to add checks.
Instead of running checks with tests, they are run during a pre commit hook (I deactivated this here)
It contains more checkers than pep8 and flake. It checks against most if not all plone.api conventions.
It is slightly configurable but mostly opiniated towards the plone.api conventions which are strict PEP8 plus more.
http://docs.plone.org/external/plone.api/docs/contribute/index.html#conventions

**Pull request closed without merging**
