### PR TITLE
Problem: buildout 3.0 cli has a new arg

### PR DESCRIPTION
**Pull request by gotcha**
Solution: support it

See https://github.com/buildout/buildout/issues/515

### CODE REVIEW

**Comment by gotcha** [comment]
It seems the only check that fails is coverage.

**Comment by fschulze** [comment]
Sorry, this got buried. A changelog entry would be nice and some time for me to try it and make a release. This weekend looks good.

**Comment by fschulze** [comment]
I've finally looked into this. I'm not sure this PR is correct or it might just be incomplete. My understanding of ``--restart-after-upgrade`` is that it is something internal to buildout which is only used to prevent an infinite loop on update of zc.buildout itself. So I'm confused in how it can end up in mr.developer. I wasn't able to create a failure condition. If the option indeed ends up in mr.developer, then it should be filtered when the command line is stored in ``.mr.developer.cfg``, otherwise every call to ``develop rebuild`` would add the option again, which to my understanding would be wrong. I also noticed that there are existing tests for ``parse_buildout_args`` which should be expanded if this stays in.

**Comment by fschulze** [comment]
Today I got ``--restart-after-upgrade`` to trigger and it is like I thought: The option is stored in ``.mr.developer.cfg``. Either it should be filtered out in the ``save`` method of ``common.Config`` or there should be a flag added to ``parse_buildout_args`` to skip it from being added to ``options`` and that flag should be set when used in the ``save`` method.

**Comment by gotcha** [comment]
I guess I was too impatient whan I tried to fix. Thanks for the details. (I did not know about ``develop rebuild``.)

I think you are right that it needs to be filtered out. I'll work on this later if nobody does it before me ;-)

**Comment by mauritsvanrees** [comment]
@gotcha Did you get a chance to look at this again? I wanted to try Plone coredev 6 with latest buildout, but failed with this mr.developer problem.

Can you rebase on master, and make sure your changelog entry ends up in the right place? I made a long overdue release, and did a Travis fix.

**Comment by fschulze** [comment]
@mauritsvanrees I know that he is away til mid September

**Comment by gotcha** [comment]
@fschulze @mauritsvanrees 

I wonder if the best way to solve this issue would not be to leave mr.developer as is but rather change buildout 3.0.
IOW, signaling the restart after update by using an environment variable rather than a command-line option when restarting buildout after buildout update. Opinions ?

**Comment by fschulze** [comment]
That sounds like a much better solution.

**Comment by gotcha** [comment]
Fix has been merged in buildout

**Pull request closed without merging**
