### PR TITLE
Bootstrap simplification & cleanup

### PR DESCRIPTION
**Pull request by reinout**
Removed if/else in the two shell scripts that detect python 2.4. I'm assuming python 2.6+ (as tested in travis/tox).

There's also only one bootstrap left as the python 2.4 one for buildout 1.7.1 isn't needed anymore.

Travis updates (`easy_install -U py`) py and setuptools. I've removed that, but that'll need a test run on travis. py is installed by buildout, so it should be unnecessary. And the newest bootstrap.py isolates buildout well enough from system setuptools versions.

Note: the version pins seem a bit weird. Some flake extensions are pinned, some not, for instance. Shall I just pin everything? Or is it done this way for a reason?

### CODE REVIEW

**Comment by fschulze** [comment]
I'm not sure about cutting off 2.4 and 2.5. I was thinking about it for some time now. I guess if an old buildout still uses mr.developer, then it will continue to work for some time if pinned to an old version. But if we do this, then I think we should follow semantic versioning and bump to 2.0.0 to indicate a backward incompatible change and add it in the changelog (both the cut and that we will follow semantic versioning). Since there is no working test environment for Python 2.4 and 2.5 it sounds kind of necessary to do this step now.

**Comment by reinout** [comment]
I think nobody expects mr.developer to keep up-to-date with python 2.4/2.5, at least I was quite surprised it actually still worked with 2.4 :-)

For mr.developer itself, it isn't really a backwards incompatible change. To me, such a change would mean a different format of the buildout configuration. Mr.developer still works in the same way as before, it "only" doesn't work anymore with buildout 1.4 or 1.7. And nobody's supporting those buildout versions.

**Comment by fschulze** [comment]
Ok, but I still want it prominently shown in the changelog.

And in ``get_text_from_file`` we can now unconditionally decode from ``utf-8`` if I'm not mistaken.

**Comment by fschulze** [comment]
Oh, and it still works with the old buildout versions (for now), only Python 2.4 and 2.5 aren't supported anymore.

**Comment by reinout** [comment]
I've made the get_text_from_file decoding unconditional and I added a changelog. You might want to check the wording in the changelog to see if it is prominent/friendly enough.

**Pull request merged**
