### PR TITLE
Add shell command

### PR DESCRIPTION
**Pull request by gforcada**
Runs an arbitrary command on all active sources.

Fixes https://github.com/fschulze/mr.developer/issues/90

### CODE REVIEW

**Comment by fschulze** [comment]
I think this should first be done as a plugin and used for a while. In this state it's pretty limited. Adding options like running on everything checked out source instead of only the active ones or limiting the sources by name aren't easily possible at the moment. I'm also not sure whether you could easily add options and arguments, or if you would have to separate the ``cmd`` with double dashes.

I still think it's better to use the regular shell features with the ``develop list`` command, like:

```for name in $(develop list -d); do ...; done```

With that you also get well defined behaviour for variable escaping, filename globbing and piping of several commands.

**Comment by gforcada** [comment]
I did it minimal just to make it easier to be reviewed, check if the approach was the correct one and so on.

And actually if I wrote this is basically because I'm tired of doing exactly what you just typed, I want to type less characters to run something on all packages.

That's specially important when I do cleanups or grepping for things and so on.

I can create a separate distribution if you want, sure no problem on that.

**Comment by mauritsvanrees** [comment]
I am inclined to agree that this is better done as a plugin. I have not tried creating plugins for mr.developer, but for example for zest.releaser the possibility to create plugins works quite well.

It currently looks small enough, but if we would add this to the core, it has the danger of growing more and more options. For example, it would probably make sense to then be able to add a command or a list of commands somewhere in the main config, like this:

```
  [buildout]
  develop_shell_command =
      pwd
      ls
```

And people may want to override this per source:

```
  [sources]
  package = git git@somewhere/package shell_command='git log -l3'
```

All fine additions, but this complexity is better placed in an add-on, keeping the core lean.

**Comment by fschulze** [comment]
As far as I know there was the question on how to create a plugin. The author contacted me because he couldn't get a plugin to be picked up by mr.developer. I didn't have time to investigate yet.

**Comment by mauritsvanrees** [comment]
I am closing this, as we concluded this should be tried outside of mr.developer.

**Pull request closed without merging**
